name: CI

on:
#  push:
#    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.9.3
    - name: Bump Helm Chart Version
      run: |
        #!/bin/bash
        set -x
        python3 -m pip install pybump
        charts=$(ls -d charts/*/ | awk -F/ '{print $2}')
        #echo $charts
        for chart in $charts;
        do
          #echo $chart
          chart_ver=$(yq '.version' charts/$chart/Chart.yaml);
          chart_changes="$(git diff --name-only HEAD $chart-$chart_ver -- charts/$chart)";
          if [ ! -z "$chart_changes" ];
          then
            pybump bump --file charts/$chart/Chart.yaml --level patch --quiet
            new_version=$(jq '.version' charts/$chart/Chart.yaml )
            git add charts/$chart/Chart.yaml
            git commit -m "Bump $chart version $new_version"
            git push
          fi
        done
    - name: Helm Chart Releaser
      uses: helm/chart-releaser-action@v1.2.1
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
